vit/ViewModels/MembersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using vit.Entities;

namespace vit.ViewModels
{
    public class MembersViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ParentId { get; set; }
        public int? Age { get; set; }
        public string Education { get; set; }
        public string CellPhone { get; set; }
        public string Profession { get; set; }
        public string Avatar { get; set; }
        public bool? MaritialStatus { get; set; }
        public bool? IsAlive { get; set; }
        public VillageMembers Parent { get; set; }
        public int TotalKids { get; set; }
        public bool HaveKids { get; set; }  
    }
}

vit/Controllers/MembersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using vit.Data;
using vit.DataAccess.Interfaces;
using vit.ViewModels;
using vit.Entities;

namespace vit.Controllers
{
    [Route("[controller]/[action]")]
    public class MembersController : Controller
    {
        private IVillageMembersRepository _repo;

        public MembersController(IVillageMembersRepository repo)
        {
            _repo = repo;  
        }
        public ActionResult Index(string searchby, string Search)
        {
            var model = _repo.GetAllIncluding(x => x.Parent);

            if (searchby == null && Search == null)
            {
                return View(model);
            }

            switch (searchby)
            {
                case "Name":
                    model = model.Where(x => x.Name.Contains(Search));
                    return View(model);
                case "Age":
                    model = model.Where(x => x.Age.ToString() == Search);
                    return View(model); 
                case "Education":
                    model = model.Where(x => x.Education.Contains(Search));
                    return View(model);
            }

            return View(model);
        }
    }
}
 

vit/Views/Members/Index.cshtml
@model IEnumerable<vit.Entities.VillageMembers>
@{
    ViewData["Title"] = "All Members";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
} 
<h2></h2>




<form asp-controller="Members" class="form-inline" asp-action="Index" method="get">
    <div class="container">
        <label class="radio-inline">
            <input type="radio" name="searchby" value="Name" checked>
            Name
        </label>

        <label class="radio-inline">
            <input type="radio" name="searchby" value="Age">
            Age
        </label>

        <label class="radio-inline">
            <input type="radio" name="searchby" id="Radios3" value="Education">
            Education
        </label>
    </div>
    <div class="form-group">
        <input type="text" class="form-control empty" name="Search" id="iconified" placeholder="&#xF002; serach" />
    </div>
</form>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Name
            </th>
            <th>
                Parent Name
            </th>
            <th>
                Age
            </th>
            <th>
                Educations
            </th>
            <th>
                Cell #
            </th>
            <th>
                Profession
            </th>

            <th>
                Married
            </th>
            <th>
                Alive
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var married = (item.MaritialStatus == true) ? "glyphicon-thumbs-up" : "glyphicon-thumbs-down";
            var alive = item.IsAlive == true ? "glyphicon-thumbs-up" : "glyphicon-thumbs-down";


            <tr>
                <td>
                    @(i++)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Parent.Name)
                    @if (item.Parent == null)
                    {
                        <i class="fa fa-times fa-2x text-center" aria-hidden="true"></i>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                    @if (item.Age == null)
                    {
                        <i class="fa fa-times fa-2x text-center" aria-hidden="true"></i>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Education)
                    @if (item.Education == null)
                    {
                        <i class="fa fa-times fa-2x text-center" aria-hidden="true"></i>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CellPhone)
                    @if (item.CellPhone == null)
                    {
                        <i class="fa fa-times fa-2x text-center" aria-hidden="true"></i>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Profession)
                    @if (item.Profession == null)
                    {
                        <i class="fa fa-times fa-2x text-center" aria-hidden="true"></i>
                    }
                </td>

                <td class="text-center">
                    <span class="glyphicon @married"></span>
                </td>
                <td>
                    <span class="glyphicon @alive"></span>
                </td>
            </tr>
        }
    </tbody>
</table>